language: php

php:
  - 5.4

mysql:
  database: drupal
  username: root
  encoding: utf8

install:
  - sudo apt-get update > /dev/null
  - "mysql -e 'create database drupal;'"

  - pear channel-discover pear.drush.org
  - pear install drush/drush-5.9.0
  - phpenv rehash

  # Build Behat dependencies
  - cd ./tests/behat
  - composer install
  - touch behat.local.yml
  - cd ../../../

  # Build Codebase
  - mkdir private_files
  - mkdir profiles
  - mv vih-behat profiles/
  - mkdir drupal
  - mv profiles drupal/

  # Test the current branch
  - cd drupal
  # - echo "projects[vih_dk][download][branch] = $TRAVIS_BRANCH" >> profiles/vih-behat/vih-behat_distro.make
  - drush make profiles/vih-behat/build-vih.make --yes
  # - cp profiles/vih-behat/settings.php.example sites/default/settings.php
  # - cp profiles/vih-behat/settings.local.php.example sites/default/settings.local.php
  - cd ../

  # Setup files
  - mkdir drupal/sites/default/files
  - mkdir drupal/sites/default/private_files
  - sudo chmod -R 777 drupal/sites/all/modules

  # Setup display for Selenium
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5

  # Get Selenium
  - wget http://selenium.googlecode.com/files/selenium-server-standalone-2.33.0.jar
  - java -jar selenium-server-standalone-2.33.0.jar > /dev/null 2>&1 &
  - sleep 5

before_script:

  - cd drupal
  - php -d sendmail_path=/dev/null `which drush` si vih_dk --db-url=mysql://root:@127.0.0.1/drupal --account-name=admin --account-pass=VIH@2012 --site-mail=admin@example.com --site-name="vih.dk" --yes
  - drush runserver --server=builtin 8888 > /dev/null &
  - sleep 3
  - cd profiles/vih-behat/tests/behat

script:

  - ./bin/behat